modLoader="javafml"
loaderVersion="[1,)"
issueTrackerURL="https://github.com/CreativeMD/LittleTilesImportOld/issues"
license="LGPL-3.0-only"

[[mods]]
    modId="littletilesimportold"
    logoFile="littletilesimportold.png"
    version="1.0.3"
    displayName="LittleTilesImportOld"
    displayURL="https://modrinth.com/mod/littletilesimportold"
    authors="CreativeMD"
    description='''An addon for LittleTiles to be able to import worlds from 1.12.'''

[[dependencies.littletilesimportold]]
    modId="neoforge"
    type="required"
    versionRange="[21.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.littletilesimportold]]
    modId="minecraft"
    type="required"
    versionRange="[1.21,1.22)"
    ordering="NONE"
    side="BOTH"

[[dependencies.littletilesimportold]]
   modId="creativecore"
   type="required"
   ordering="NONE"
   side="BOTH"
   versionRange="2.12.0"

[[dependencies.littletilesimportold]]
   modId="littletiles"
   type="required"
   ordering="NONE"
   side="BOTH"
   versionRange="[1.6,)"

[[mixins]]
   config="littletilesimportold.mixins.json"

